name: Deploy Flutter Web to AWS S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Build Web
        run: |
          flutter clean
          flutter pub get
          flutter build web --release --no-tree-shake-icons --web-renderer canvaskit

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          folder: build/web
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          args: |
            --size-only \
            --delete \
            --exclude ".dart_tool/*" \
            --exclude ".git/*" \
            --exclude "*.map"
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}  # Explicit environment variable
