name: Deploy Flutter Web to AWS S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'  # Verified stable version
          channel: stable

      - name: Update Web Configuration
        run: |
          rm -rf web
          flutter create --platforms web .

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Web Release
        run: |
          flutter build web \
            --release \
            --no-tree-shake-icons \
            --dart-define=FLUTTER_WEB_USE_SKIA=true

      - name: Verify Build Output
        run: ls -lah build/web

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --size-only --delete
          folder: build/web
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-south-1
