name: Deploy Flutter Web to AWS S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Build Web App
        run: |
          flutter clean
          flutter pub get
          flutter build web --release --no-tree-shake-icons --web-renderer canvaskit

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        env:
          # Ensure that this secret is set in your repo's Secrets (Settings > Secrets and variables > Actions)
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: sync build/web s3://${{ secrets.S3_BUCKET_NAME }} \
                --size-only \
                --delete \
                --exclude ".dart_tool/*" \
                --exclude ".git/*" \
                --exclude "*.map" \
                --exclude "*.symbols"
